### ISSUE TITLE
Mod API Documentation

### ISSUE THREAD

**Issue by CodeZwei** [DPMakerQB/queens-brothel-mod#4]
Is there a specific place you are planning to document the Mod API?

Before 0.10.3 there was a `qbManager` directory in this repo which I am assuming was a copy of some of the engine code from another repo. Though I am sure it was annoying to have to keep that directory up to date, it was a very useful reference for various mod APIs not showcased in the example mods.

Are you going to provide another documentation location?

----

As an alternative to manually maintaining documentation, have you consider converting the source to [TypeScript](https://www.typescriptlang.org/)? Typescript is a super-set of Javascript but comes with a strong type system. The TypeScript compiler can automatically generate a `typings` file for your project which you can publish which will allow editors to discover mod APIs.

**Comment by DPMakerQB** [comment]
Hello again CodeZwei, I do have a documentation page for the API [https://queensbrothel.com/modding/](https://queensbrothel.com/modding/). And my bad, I somehow didn't push the managers into the repository. I do find it a little annoying to add them, but I think it's useful so I'll leave it in there.

Yes, I believe Phaser 4 will be built using TypeScript and in the future I thought it would be really fun to rewrite the game in TypeScript for the new engine. But, I'll continue chugging along with jsdoc for now.

**Comment by CodeZwei** [comment]
Oh I see, actually that documentation page is quite useful! I'd take that over keeping the managers in this repo.

That said I would enjoy having TypeScript typings for in-editor completions but that modding page is good too.
